//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFcursusH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursus
    {
        public Cursus()
        {
            this.BoekenCursussen2 = new HashSet<BoekCursus>();
        }
    
        public int CursusNr { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<BoekCursus> BoekenCursussen2 { get; set; }
    }
}
