//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFcursusH2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursist
    {
        public Cursist()
        {
            this.Beschremelingen = new HashSet<Cursist>();
        }
    
        public int CursistNr { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public Nullable<int> MentorNr { get; set; }
    
        public virtual ICollection<Cursist> Beschremelingen { get; set; }
        public virtual Cursist Mentor { get; set; }
    }
}
