//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFcursusH2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Opleidingen2Entities : DbContext
    {
        public Opleidingen2Entities()
            : base("name=Opleidingen2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campus> Campussen { get; set; }
        public virtual DbSet<Docent> Docenten { get; set; }
        public virtual DbSet<Boek> Boeken { get; set; }
        public virtual DbSet<BoekCursus> BoekenCursussen { get; set; }
        public virtual DbSet<Cursus> Cursussen { get; set; }
    }
}
