//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCollection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameCollectionDBContainer : DbContext
    {
        public GameCollectionDBContainer()
            : base("name=GameCollectionDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> GameSet { get; set; }
        public virtual DbSet<ConsoleSoort> ConsoleSoortSet { get; set; }
        public virtual DbSet<Platform> PlatformSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Collection> CollectionSet { get; set; }
        public virtual DbSet<GameCollectionUI> GameCollectionUIs { get; set; }
    }
}
