//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCollectionUI
    {
        public int Id { get; set; }
        public int Games_Id { get; set; }
        public int Collection_id { get; set; }
        public string Condition { get; set; }
        public string Version { get; set; }
    
        public virtual Collection CollectionSet { get; set; }
        public virtual Game GameSet { get; set; }
    }
}
