//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameCollectionUIs = new HashSet<GameCollectionUI>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int ConsoleSoort_Id { get; set; }
        public string BoxArtLocation { get; set; }
    
        public virtual ConsoleSoort ConsoleSoort { get; set; }
        public virtual ICollection<GameCollectionUI> GameCollectionUIs { get; set; }
    }
}
